# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Zybo-Z7-Master.xdc

# Block Designs: bd/tdoa/tdoa.bd
# Block Designs: The module: 'tdoa' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/tdoa/ip/tdoa_processing_system7_0_2/tdoa_processing_system7_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tdoa_processing_system7_0_2 || ORIG_REF_NAME==tdoa_processing_system7_0_2} -quiet] -quiet

# IP: bd/tdoa/ip/tdoa_axi_channel_demux_0_1/tdoa_axi_channel_demux_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tdoa_axi_channel_demux_0_1 || ORIG_REF_NAME==tdoa_axi_channel_demux_0_1} -quiet] -quiet

# IP: bd/tdoa/ip/tdoa_system_ila_0_0/tdoa_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tdoa_system_ila_0_0 || ORIG_REF_NAME==tdoa_system_ila_0_0} -quiet] -quiet

# Block Designs: /media/psf/TAUV-Playground/zybo-z7-tdoa/zybo-z7-tdoa/zybo-z7-tdoa.gen/sources_1/bd/tdoa/ip/tdoa_system_ila_0_0/bd_0/bd_64f5.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_64f5 || ORIG_REF_NAME==bd_64f5} -quiet] -quiet

# IP: /media/psf/TAUV-Playground/zybo-z7-tdoa/zybo-z7-tdoa/zybo-z7-tdoa.gen/sources_1/bd/tdoa/ip/tdoa_system_ila_0_0/bd_0/ip/ip_0/bd_64f5_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_64f5_ila_lib_0 || ORIG_REF_NAME==bd_64f5_ila_lib_0} -quiet] -quiet

# IP: /media/psf/TAUV-Playground/zybo-z7-tdoa/zybo-z7-tdoa/zybo-z7-tdoa.gen/sources_1/bd/tdoa/ip/tdoa_system_ila_0_0/bd_0/ip/ip_1/bd_64f5_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_64f5_g_inst_0 || ORIG_REF_NAME==bd_64f5_g_inst_0} -quiet] -quiet

# IP: bd/tdoa/ip/tdoa_util_vector_logic_0_0/tdoa_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tdoa_util_vector_logic_0_0 || ORIG_REF_NAME==tdoa_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/tdoa/ip/tdoa_proc_sys_reset_0_0/tdoa_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tdoa_proc_sys_reset_0_0 || ORIG_REF_NAME==tdoa_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/tdoa/ip/tdoa_axi_xadc_sampler_0_3/tdoa_axi_xadc_sampler_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tdoa_axi_xadc_sampler_0_3 || ORIG_REF_NAME==tdoa_axi_xadc_sampler_0_3} -quiet] -quiet

# IP: /media/psf/TAUV-Playground/zybo-z7-tdoa/zybo-z7-tdoa/zybo-z7-tdoa.gen/sources_1/bd/tdoa/ip/tdoa_axi_xadc_sampler_0_3/src/xadc_wiz_0_3/xadc_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xadc_wiz_0 || ORIG_REF_NAME==xadc_wiz_0} -quiet] -quiet

# IP: bd/tdoa/ip/tdoa_led_debug_0_0/tdoa_led_debug_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tdoa_led_debug_0_0 || ORIG_REF_NAME==tdoa_led_debug_0_0} -quiet] -quiet

# IP: bd/tdoa/ip/tdoa_axi_fsk_demod_0_4/tdoa_axi_fsk_demod_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tdoa_axi_fsk_demod_0_4 || ORIG_REF_NAME==tdoa_axi_fsk_demod_0_4} -quiet] -quiet

# IP: bd/tdoa/ip/tdoa_axi_fsk_demod_0_5/tdoa_axi_fsk_demod_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tdoa_axi_fsk_demod_0_5 || ORIG_REF_NAME==tdoa_axi_fsk_demod_0_5} -quiet] -quiet

# IP: bd/tdoa/ip/tdoa_axi_fsk_demod_0_6/tdoa_axi_fsk_demod_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tdoa_axi_fsk_demod_0_6 || ORIG_REF_NAME==tdoa_axi_fsk_demod_0_6} -quiet] -quiet

# IP: bd/tdoa/ip/tdoa_axi_fsk_demod_0_7/tdoa_axi_fsk_demod_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tdoa_axi_fsk_demod_0_7 || ORIG_REF_NAME==tdoa_axi_fsk_demod_0_7} -quiet] -quiet

# XDC: /media/psf/TAUV-Playground/zybo-z7-tdoa/zybo-z7-tdoa/zybo-z7-tdoa.gen/sources_1/bd/tdoa/ip/tdoa_processing_system7_0_2/tdoa_processing_system7_0_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tdoa_processing_system7_0_2 || ORIG_REF_NAME==tdoa_processing_system7_0_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/psf/TAUV-Playground/zybo-z7-tdoa/zybo-z7-tdoa/zybo-z7-tdoa.gen/sources_1/bd/tdoa/ip/tdoa_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_64f5_ila_lib_0 || ORIG_REF_NAME==bd_64f5_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/psf/TAUV-Playground/zybo-z7-tdoa/zybo-z7-tdoa/zybo-z7-tdoa.gen/sources_1/bd/tdoa/ip/tdoa_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_64f5_ila_lib_0 || ORIG_REF_NAME==bd_64f5_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/psf/TAUV-Playground/zybo-z7-tdoa/zybo-z7-tdoa/zybo-z7-tdoa.gen/sources_1/bd/tdoa/ip/tdoa_system_ila_0_0/bd_0/ip/ip_0/bd_64f5_ila_lib_0_ooc.xdc

# XDC: /media/psf/TAUV-Playground/zybo-z7-tdoa/zybo-z7-tdoa/zybo-z7-tdoa.gen/sources_1/bd/tdoa/ip/tdoa_system_ila_0_0/bd_0/bd_64f5_ooc.xdc

# XDC: /media/psf/TAUV-Playground/zybo-z7-tdoa/zybo-z7-tdoa/zybo-z7-tdoa.gen/sources_1/bd/tdoa/ip/tdoa_system_ila_0_0/tdoa_system_ila_0_0_ooc.xdc

# XDC: /media/psf/TAUV-Playground/zybo-z7-tdoa/zybo-z7-tdoa/zybo-z7-tdoa.gen/sources_1/bd/tdoa/ip/tdoa_proc_sys_reset_0_0/tdoa_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tdoa_proc_sys_reset_0_0 || ORIG_REF_NAME==tdoa_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/psf/TAUV-Playground/zybo-z7-tdoa/zybo-z7-tdoa/zybo-z7-tdoa.gen/sources_1/bd/tdoa/ip/tdoa_proc_sys_reset_0_0/tdoa_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tdoa_proc_sys_reset_0_0 || ORIG_REF_NAME==tdoa_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/psf/TAUV-Playground/zybo-z7-tdoa/zybo-z7-tdoa/zybo-z7-tdoa.gen/sources_1/bd/tdoa/ip/tdoa_axi_xadc_sampler_0_3/src/xadc_wiz_0_3/xadc_wiz_0_ooc.xdc

# XDC: /media/psf/TAUV-Playground/zybo-z7-tdoa/zybo-z7-tdoa/zybo-z7-tdoa.gen/sources_1/bd/tdoa/ip/tdoa_axi_xadc_sampler_0_3/src/xadc_wiz_0_3/xadc_wiz_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xadc_wiz_0 || ORIG_REF_NAME==xadc_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/psf/TAUV-Playground/zybo-z7-tdoa/zybo-z7-tdoa/zybo-z7-tdoa.gen/sources_1/bd/tdoa/tdoa_ooc.xdc
